export { default as Home } from './Home'
export { default as Plans } from './Plans'
export { default as Trainers } from './Trainers'
export { default as Members } from './Members'
export { default as Equipent } from './Equipment'